---
# tasks file for lynis

- name: Create directories
  file: name={{item}} state=directory owner=root group=root mode=0755
  with_items:
    - /etc/lynis

- name: Import gpg keys
  rpm_key: state=present key={{item}} validate_certs={{validate_certs|default('yes')}}
  with_items:
    - https://packages.cisofy.com/keys/cisofy-software-rpms-public.key
  when: ansible_os_family == 'RedHat'

- name: Yum repository
  template: src="{{item.src}}" dest="{{item.dest}}" owner={{item.owner|default('root')}}  group="{{item.group|default('root')}}" mode="{{item.mode|default('0644')}}"
  with_items:
    - { src: "lynis.repo", dest: "/etc/yum.repos.d/lynis.repo" }
  register: lynis_repo_rpm
  when: ansible_os_family == 'RedHat'

- name: Install Apt-keys
  apt_key: keyserver="{{item.keyserver|default('keyserver.ubuntu.com')}}" id="{{item.id}}"
  with_items:
    - { id: "C80E383C3DE9F082E01391A0366C67DE91CA5D5F", comment: "Lynis" }
  when: ansible_os_family == 'Debian'

- name: Apt repository
  template: src="{{item.src}}" dest="{{item.dest}}" owner={{item.owner|default('root')}}  group="{{item.group|default('root')}}" mode="{{item.mode|default('0644')}}"
  with_items:
    - { src: "lynis.list", dest: "/etc/apt/sources.list.d/lynis.list" }
  when: ansible_os_family == 'Debian'
  register: lynis_repo_apt

- name: Reload apt-caches
  apt:
    update_cache: yes
  when: ansible_os_family == 'Debian' and lynis_repo_apt is changed

- name: Install lynis packages
  package:
    name: "{{item}}"
    state: latest
  with_items:
    - lynis
    - "{% if ansible_os_family == 'Debian' %}apt-transport-https{% else %}[]{% endif %}"
    - curl
    - "{% if lynis_license_key %}lynis-plugins{%else%}[]{% endif %}"

- name: Template configuration-files
  template: src="{{item.src}}" dest="{{item.dest}}" owner="{{item.owner|default('root')}}" group="{{item.group|default('root')}}" mode="{{item.perm|default('0755')}}"
  with_items:
    - { src: "lynis-custom.prf.j2", dest: "/etc/lynis/custom.prf", mode: "0644" }

- name: Find path for lynis binary (different on EL)
  command: "which lynis"
  check_mode: no
  register: lynis_path
  changed_when: false

- name: Set lynis_binary path
  set_fact:
    lynis_binary: "{{lynis_path.stdout}}"
    cacheable: true
  check_mode: yes

- name: Setup cronjob for lynis
  cron:
      cron_file: lynis
      user: root
      hour: "3"
      minute: "10"
      name: "nightly Lynis run"
      state: present
      job: "{{lynis_binary}} audit system --upload > /dev/null"
  ignore_errors: yes

- name: Generate hostid values
  command:
    creates: /etc/lynis/hostids
    argv:
      - lynis generate hostids --save
  when:
    - lynis_generate_hostids|bool
  tags:
    - lynishostids
